apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql-core
spec:
  selector:
    matchLabels:
      app: postgresql-core
  template:
    metadata:
      labels:
        app: postgresql-core
    spec:
      containers:
      - name: postgresql-core
        image: postgres:latest
        env:
        - name: POSTGRES_DB
          value: "sciencehub_database"
        - name: POSTGRES_USER
          value: "postgres"
        - name: POSTGRES_PASSWORD
          value: "example-password"
        ports:
        - containerPort: 5432
        volumeMounts:
        - mountPath: /docker-entrypoint-initdb.d
          name: db-dump
      volumes:
      - name: db-dump
        configMap:
          name: postgresql-core-initdb
---
apiVersion: v1
kind: Service
metadata:
  name: postgresql-core-service
spec:
  selector:
    app: postgresql-core
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432