apiVersion: apps/v1
kind: Deployment
metadata:
  name: sciencehub-backend-community
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sciencehub-backend-community
  template:
    metadata:
      labels:
        app: sciencehub-backend-community
    spec:
      containers:
      - name: sciencehub-backend-community
        image: tudoraorban/sciencehub-backend-community:latest
        ports:
        - containerPort: 8081
        imagePullPolicy: IfNotPresent
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Production"
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1024Mi"
            cpu: "1000m"
---
apiVersion: v1
kind: Service
metadata:
  name: sciencehub-backend-community-service
spec:
  type: NodePort
  ports:
    - port: 8081
      targetPort: 8081
      nodePort: 31881
  selector:
    app: sciencehub-backend-community