apiVersion: apps/v1
kind: Deployment
metadata:
  name: sciencehub-core
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sciencehub-core
  template:
    metadata:
      labels:
        app: sciencehub-core
    spec:
      containers:
      - name: sciencehub-core
        image: tudoraorban/sciencehub-core:latest
        ports:
        - containerPort: 8080
        imagePullPolicy: IfNotPresent
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: Production
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1024Mi"
            cpu: "1000m"
---
apiVersion: v1
kind: Service
metadata:
  name: sciencehub-core-service
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 31880
  selector:
    app: sciencehub-core