apiVersion: apps/v1
kind: Deployment
metadata:
  name: sciencehub-api-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sciencehub-api-gateway
  template:
    metadata:
      labels:
        app: sciencehub-api-gateway
    spec:
      containers:
      - name: sciencehub-api-gateway
        image: tudoraorban/sciencehub-api-gateway:latest
        ports:
        - containerPort: 8082
        imagePullPolicy: IfNotPresent
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Production"
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1024Mi"
            cpu: "1000m"
---
apiVersion: v1
kind: Service
metadata:
  name: sciencehub-api-gateway-service
spec:
  type: NodePort
  ports:
    - port: 8082
      targetPort: 8082
      nodePort: 31882
  selector:
    app: sciencehub-api-gateway